### ISSUE TITLE
Repeating socket disconnected error when webpack process killed

### ISSUE THREAD

**Issue by ybentz** [rubenspgcavalcante/webpack-extension-reloader#30]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: macOS
  - Browser: Chrome 
  - Library Version: v1.1.0

**I'm going to open a PR:**
  - [ ] yes
  - [x] no

**Description:**
Awesome plugin! Thanks for writing it.
Seems like when the webpack (v4) in development+watch mode process gets killed the socket is not being closed causing the extension's background script to keep throwing errors trying to connect. It doesn't stop trying until webpack is ran again and the socket is available.
Here's a [link](https://github.com/rubenspgcavalcante/webpack-extension-reloader/blob/e1089c5f6032be0cc9d197067de725ee18c71049/src/middleware/wer-middleware.raw.ts#L100) to where it happens in the code.

![image](https://user-images.githubusercontent.com/14811577/61915162-2822c300-aef8-11e9-9d33-6d28f0782ba1.png)

* I marked that I'm not going to open a PR but I'd be happy to work on it when I have some time if you can't.

**Comment by k1nghat** [comment]
@ybentz do you have a workaround for the time being?

**Comment by ybentz** [comment]
Sorry, haven't had the time to try so for now I just ignore the errors.

**Comment by rhaksw** [comment]
I forked this, deleted the code that tries to reconnect, and converted one warning message to a regular log entry. This gets rid of the errors from when you stop the watch process. I am not sure what other side effects it might have. Use at your own risk. You can add this version to your project via `yarn remove webpack-extension-reloader && yarn add -D https://github.com/rhaksw/webpack-extension-reloader.git`

My process for developing extensions is now,

1. `NODE_ENV=development webpack --watch`
2. Hit the reload icon on the extension's box in `chrome://extensions/` (or `Load unpacked` if I haven't yet loaded the folder)
3. Reload any impacted pages
4. Develop as normal, steps 2 and 3 happen automatically

I'm also able to suspend my machine and come back to it without having to redo steps 1-3, running Ubuntu 19.04.

**Comment by rhaksw** [comment]
I dug into this a little deeper and it appears this type of error [cannot be hidden](https://stackoverflow.com/questions/31002592/javascript-doesnt-catch-error-in-websocket-instantiation/31003057#31003057). I guess the hint in the code `Attempting to reconnect (tip: Check if Webpack is running)` is suggesting the fix would be to check if Webpack is running before attempting the connection. Since I am developing extensions alongside a website, I often have another instance of webpack running for the site. I'm not sure how to check if webpack is running for a specific project. Perhaps there is a way to do it.

For now, the choices appear to be,

1. ignore the errors
2. clear the errors manually after stopping and starting webpack
3. use the fork I made above which prevents reconnects, and manually reload the extension + impacted pages in Chrome whenever you restart webpack

I prefer \#3 because it's easy to remember to click reload once in the beginning, and the WebSocket connection errors make it harder for me to know if there were errors happening in my own extension's background page.

**Comment by rubenspgcavalcante** [comment]
Hello, thanks for the feedback and sorry for the delay, it has been a tough year for me :(
So why let the socket keep on retrying to connect and why I think this isn't a bug:
First, there's no way to differentiate if it went down by an error or you simply killed webpack process.
Second, I can try to send a SIGKILL to the socket inside the extension and make it stop retrying, but when you run the webpack again, how to restart it? Remember the extension will be totally isolated if it's not connected anymore. You will need to remove the extension and add it again (not good)

The error there appears because is a network error. Although the exception is catch to not show the annoying red text, Chrome wil show network errors a side of the JS one (no way on JS side to not make it show)

As there's no good solution for this, just ignore it, whenever you connect again the socket will successfully connect to webpack-extension-reloader and all will be fine :)
